azs:
  - name: z1
    cloud_properties:
      zone: (( grab meta.tf.avail_zone ))

networks:
  - name: vault
    type: manual
    subnets:
      - range:   (( grab meta.tf.network_range ))
        gateway: (( grab meta.tf.default_gateway ))
        dns:     [(( grab meta.tf.dns ))]
        azs:     [z1]
        reserved:
          - (( concat meta.tf.network_prefix ".2 - " meta.tf.network_prefix ".3" ))
          - (( concat meta.tf.network_prefix ".7 - " meta.tf.network_prefix ".254" ))
        static:
          - (( concat meta.tf.network_prefix ".4 - " meta.tf.network_prefix ".6" ))
        cloud_properties:
          network_name:    (( grab meta.tf.network_name ))
          subnetwork_name: (( grab meta.tf.subnetwork_name ))

  - name: default
    type: manual
    subnets:
      - range:   (( grab meta.tf.network_range ))
        gateway: (( grab meta.tf.default_gateway ))
        dns:     [(( grab meta.tf.dns ))]
        azs:     [z1]
        reserved:
          - (( concat meta.tf.network_prefix ".2 - " meta.tf.network_prefix ".127" ))
        static:
          - (( concat meta.tf.network_prefix ".128 - " meta.tf.network_prefix  ".191" ))
        cloud_properties:
          network_name:    (( grab meta.tf.network_name ))
          subnetwork_name: (( grab meta.tf.subnetwork_name ))

compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: large
  workers: 5

disk_types:
  - name: default
    disk_size: 8192
    cloud_properties:
      type: pd-standard

vm_types:
  - name: default
    cloud_properties:
      machine_type: n1-standard-2
  - name: small
    cloud_properties:
      machine_type: n1-standard-1
  - name: medium
    cloud_properties:
      machine_type: n1-standard-4
  - name: large
    cloud_properties:
      machine_type: n1-standard-8
